"""add language to posts

Revision ID: 039f4b32f683
Revises: a2423d63486a
Create Date: 2022-07-22 23:19:30.714974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '039f4b32f683'
down_revision = 'a2423d63486a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
